Repository cca-ffodregamdi/running-hi-back, pull requests merged in 2023-10, with the labels that each got.

#216 [FEATURE] - {LOGGING} LOG4J2 설정
  .github/workflows/gradle.yml
  .gitignore
  build.gradle
  src/main/java/com/runninghi/common/exception/ExceptionResponseHandler.java
  src/main/java/com/runninghi/common/handler/feedback/FeedbackExceptionResponseHandler.java
  src/test/java/com/runninghi/LoggingTest.java
Labels: ✨ Feature, ⚙ Setting

#221 [Refactor] - {Admin Post} 관리자 여부 판단 위치 변경
  src/main/java/com/runninghi/adminpost/command/application/controller/AdminPostCommandController.java
  src/main/java/com/runninghi/adminpost/command/application/service/AdminPostCommandService.java
  src/main/java/com/runninghi/keyword/command/application/controller/KeywordCommandController.java
Labels: 🔨 Refactoring

#224 [Feature] - {Comment} 회원 확인 로직 추가 및 service 리팩토링
  .gitignore
  src/main/java/com/runninghi/bookmark/command/domain/service/ApiBookmarkDomainService.java
  src/main/java/com/runninghi/bookmark/command/domain/service/BookmarkCommandDomainService.java
  src/main/java/com/runninghi/comment/command/application/service/CommentCommandService.java
  src/main/java/com/runninghi/comment/command/domain/service/ApiCommentDomainService.java
  src/main/java/com/runninghi/comment/command/domain/service/CommentCommandDomainService.java
  src/main/java/com/runninghi/comment/command/infrastructure/service/ApiCommentInfraService.java
  src/main/java/com/runninghi/comment/query/application/controller/CommentQueryController.java
  src/main/java/com/runninghi/comment/query/application/controller/test.java
  src/main/java/com/runninghi/comment/query/application/dto/response/CommentQueryResponse.java
  src/main/java/com/runninghi/comment/query/application/service/CommentQueryService.java
  src/main/java/com/runninghi/comment/query/infrastructure/repository/CommentQueryRepository.java
  src/main/resources/db/data/data.sql
  src/test/java/com/runninghi/comment/command/application/service/CommentCommandServiceTests.java
  src/test/java/com/runninghi/comment/query/application/service/CommentQueryServiceTests.java
Labels: ✨ Feature, 🔨 Refactoring
